import 'package:flutter/material.dart';

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: Text("$lorem+\n$lorem"),
    );
  }
}

const lorem = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pellentesque placerat accumsan. Phasellus rhoncus mi quis tempor feugiat. Donec laoreet eros at tellus dictum commodo. Morbi vehicula enim et lorem rutrum, nec ultricies elit condimentum. Praesent ac lectus libero. Vestibulum vitae diam quis erat sagittis placerat. Nunc tincidunt ex nisl, in mollis nulla egestas eget. Vivamus lobortis, eros a lobortis viverra, orci diam eleifend nunc, eget pharetra magna turpis et ante. Nunc hendrerit condimentum nisl, sagittis pellentesque ante scelerisque sed. Fusce maximus interdum ligula, ac blandit erat faucibus ut. Aliquam sed orci pellentesque, luctus neque eu, tristique turpis. Etiam suscipit commodo venenatis.

Integer tincidunt sapien vitae quam rutrum, non vehicula nisi blandit. Proin arcu nulla, viverra eget leo ut, hendrerit dignissim ante. Pellentesque nec nunc dignissim, gravida metus at, dapibus nisi. Nam ultrices elit vitae tempor venenatis. In hac habitasse platea dictumst. Etiam non ligula ut dui convallis hendrerit sit amet dictum velit. Proin malesuada ac urna vitae facilisis. Donec at sapien in libero sodales auctor a id leo. Quisque nec libero in erat imperdiet fringilla. Nam sed diam ante.

Nulla consequat eget massa ut pretium. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti. Phasellus et blandit ex, id malesuada lacus. Nam sodales tellus non condimentum pretium. Fusce euismod luctus bibendum. Vestibulum odio sem, interdum posuere turpis at, bibendum viverra mauris. Curabitur sagittis iaculis urna vitae consequat. Nulla facilisi. Donec eu augue dolor. Morbi a varius risus. Morbi rutrum venenatis urna, non bibendum magna. Duis efficitur neque vel ligula vehicula, eu vulputate ex dapibus. In posuere, risus id ultrices eleifend, mi lectus placerat sem, at ultrices lectus felis id lectus. Nullam tincidunt enim non felis vulputate volutpat. Fusce eu urna a enim fringilla mattis ac hendrerit sem.

Praesent eget turpis ut risus sagittis egestas vel non orci. Vivamus rutrum auctor erat. Cras efficitur augue ac tellus dictum luctus. Donec suscipit ligula sit amet lectus accumsan porta. Aenean et finibus nisl. Proin vestibulum tristique magna, eu blandit risus lobortis a. Vivamus id arcu quis erat tincidunt pretium sed elementum orci. Ut pharetra, eros a eleifend consequat, libero orci dapibus lorem, maximus vulputate erat arcu eget purus. Etiam elementum varius sem, vitae sollicitudin arcu convallis eget. Donec a sem sem. Suspendisse potenti. Vestibulum facilisis quam vel convallis pellentesque. Sed tempus sit amet nulla ut tincidunt.

Nunc id risus blandit, scelerisque nisl id, eleifend justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum est ac orci tempor, vel accumsan metus mollis. Nam ultrices urna nec ante pretium, eu cursus ante aliquam. Morbi tincidunt eros ex, eu ornare lorem eleifend vel. Cras in diam accumsan, sollicitudin quam nec, mattis nibh. Fusce eget tortor id leo tincidunt posuere ut ut leo. Donec egestas sollicitudin odio, quis fermentum nulla consequat id. Etiam maximus ut arcu sed aliquet. Quisque nec viverra leo.

Curabitur quis gravida purus, in dictum orci. Fusce purus ex, pulvinar et lacus ac, blandit efficitur velit. Suspendisse vel cursus est. Sed cursus tincidunt euismod. Morbi facilisis, leo sit amet lobortis rutrum, elit elit ornare ex, vel ullamcorper risus massa non eros. Donec placerat, est ac aliquet placerat, metus quam tincidunt tortor, id volutpat massa dolor sit amet ipsum. Sed in ultrices eros, nec tempor velit. Nullam non odio pharetra, facilisis metus in, pellentesque lacus. Donec placerat elit in dui molestie, eu malesuada leo sodales. Donec ornare placerat malesuada. Pellentesque laoreet tortor libero, eu mollis orci venenatis in. Quisque tristique lorem at pharetra elementum.

Phasellus ultricies leo risus. Nunc et auctor enim, sit amet blandit elit. In hac habitasse platea dictumst. Phasellus ac venenatis dui. Vivamus vitae pharetra erat. Phasellus semper eu magna nec fringilla. Duis ut congue nunc, vitae lacinia felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis auctor arcu vitae augue elementum finibus vitae ullamcorper diam. Sed arcu metus, iaculis sit amet lacus in, ultrices convallis nibh. Proin mollis, nunc ut ullamcorper molestie, mi ex lacinia sem, non lobortis diam nisl nec mi. Duis vel lorem ullamcorper, imperdiet velit vitae, malesuada nisi. Nullam gravida massa et felis tincidunt, a tristique elit interdum. Vestibulum sed posuere nisl. Aenean quis ullamcorper augue. Ut eget nulla et est egestas mattis.

Cras fringilla, erat faucibus iaculis condimentum, felis dolor eleifend lacus, non suscipit mauris eros sit amet turpis. Mauris pretium ipsum purus, vel semper erat efficitur at. Aenean pulvinar vulputate accumsan. Suspendisse ex massa, maximus vel libero quis, volutpat mattis enim. Sed accumsan imperdiet blandit. Mauris rhoncus nulla mi, in pharetra mi pulvinar eget. Ut et ex ac purus consectetur bibendum tempor eget ex. Pellentesque at augue eu ex imperdiet lobortis at vel arcu. Donec imperdiet hendrerit orci. Proin dapibus ornare ligula, id cursus libero cursus a. Donec semper ultricies ipsum vitae malesuada. Duis risus lectus, aliquam at ultricies faucibus, vestibulum id nulla. Pellentesque lacinia ligula sit amet congue rhoncus. Aenean tempor massa eget orci malesuada tincidunt. Nulla facilisi. Maecenas scelerisque quam massa, vel imperdiet arcu maximus non.

Sed tempus libero non nisl hendrerit, at vulputate quam facilisis. Sed neque nisl, tincidunt vel metus quis, gravida aliquam elit. Duis efficitur, elit at fringilla molestie, velit orci finibus nunc, quis malesuada tellus felis a sapien. Phasellus dapibus, magna ut fringilla finibus, nunc ipsum faucibus ligula, eu sagittis libero dolor sit amet ligula. Nulla gravida dictum lectus ac facilisis. Aenean eget erat at dolor laoreet pharetra nec ac augue. Sed augue ligula, lobortis malesuada massa et, laoreet tincidunt nunc. Integer egestas, risus id sollicitudin tempor, lacus magna mattis mauris, quis ullamcorper ex dolor ut velit. Aenean in erat vel erat consequat viverra a quis justo. Morbi in purus felis. Aliquam imperdiet, mauris eget posuere volutpat, enim nisl fermentum dui, in scelerisque urna orci non nisl.

Nulla sed eros sit amet dui consequat rutrum at sit amet neque. Nam non ullamcorper ligula. Quisque vel velit odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer et risus eget ante convallis posuere. Proin molestie consequat est eu vulputate. Vestibulum ac sem tellus. Vivamus elit ligula, cursus vitae fermentum in, tempus nec libero. Fusce vitae nibh ut nisl commodo sagittis. Nunc dapibus, lectus vitae eleifend tincidunt, magna augue porttitor leo, ut volutpat lectus tortor eu dui. Maecenas vehicula molestie leo vitae auctor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam convallis ligula eu massa cursus rhoncus. """;
